globalThis.entryURL = import.meta.url;import 'unenv/runtime/polyfill/fetch.node';
import 'http';
import 'https';
import 'destr';
export { n as default } from './chunks/node-server.mjs';
import 'h3';
import 'ohmyfetch';
import 'radix3';
import 'unenv/runtime/fetch/index';
import 'hookable';
import 'scule';
import 'defu';
import 'ohash';
import 'unstorage';
import 'ufo';
